name: Deploy

on:
  push:
    tags:
      - '*.*.*'
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD_PLATFORMS: linux/amd64,linux/arm64
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PACKAGE_TAG: ${GITHUB_REF/refs\/tags\//}

jobs:
  deploy:
    if: github.run_number > 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower case image name
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:${{ env.PACKAGE_TAG }},${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=${{ github.event.repository.name }}
